core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('api/', include('api_rest.urls'), name='api_rest_urls'),
    path('', include('dever.urls', namespace='dever')),
    path('', include('login.urls')),
]

dever/urls.py
from django.urls import path
from dever.views.views_ajax import *
from dever.views.views_dever import *
from dever.views import *
from django.urls import path
from . import views

app_name = 'dever' # Defina o namespace aqui

urlpatterns = [
    path('lista/', dever_list, name='dever_list'),
    path('<int:pk>/', dever_detail, name='dever_detail'),
    path('novo/', dever_create, name='dever_create'),
    path('<int:pk>/editar/', dever_update, name='dever_update'),
    path('<int:pk>/deletar/', dever_delete, name='dever_delete'),

    # Outras rotas
    path('ajax/get-professores/<int:escola_id>/', views.get_professores_by_escola, name='get_professores_by_escola'),
    path('ajax/get-materia/<int:professor_id>/', views.get_materia_by_professor, name='get_materia_by_professor'),
    path('ajax/get-livros/<int:materia_id>/', views.get_livros_by_materia, name='get_livros_by_materia'),

    # URLs para Escola
    path('escolas/', views.lista_escolas, name='lista_escolas'),
    path('escolas/nova/', views.cria_escolas, name='cria_escolas'),
    path('escolas/<pk>/atualiza/', views.atualiza_escolas, name='atualiza_escolas'),
    path('escolas/<pk>/deleta/', views.deleta_escolas, name='deleta_escolas'),

    # URLs para Turma
    path('turma/', views.lista_turma, name='lista_turma'),
    path('turma/nova/', views.cria_turma, name='cria_turma'),
    path('turma/<pk>/atualiza/', views.atualiza_turma, name='atualiza_turma'),
    path('turma/<pk>/deleta/', views.deleta_turma, name='deleta_turma'),

    #... (Adicione URLs para Materia, , , )
    # Exemplo para Materia:
    path('materia/', views.lista_materia, name='lista_materia'),
    path('materia/nova/', views.cria_materia, name='cria_materia'),
    path('materia/<pk>/atualiza/', views.atualiza_materia, name='atualiza_materia'),
    path('materia/<pk>/deleta/', views.deleta_materia, name='deleta_materia'),

    # Exemplo para professor:
    path('professor/', views.lista_professor, name='lista_professor'),
    path('professor/nova/', views.cria_professor, name='cria_professor'),
    path('professor/<pk>/atualiza/', views.atualiza_professor, name='atualiza_professor'),
    path('professor/<pk>/deleta/', views.deleta_professor, name='deleta_professor'),

    # Exemplo para livro:
    path('livro/', views.lista_livro, name='lista_livro'),
    path('livro/nova/', views.cria_livro, name='cria_livro'),
    path('livro/<pk>/atualiza/', views.atualiza_livro, name='atualiza_livro'),
    path('livro/<pk>/deleta/', views.deleta_livro, name='deleta_livro'),

    # Exemplo para aluno:
    path('alunos/', views.lista_alunos, name='lista_alunos'),
    path('alunos/nova/', views.cria_alunos, name='cria_alunos'),
    path('alunos/<pk>/atualiza/', views.atualiza_alunos, name='atualiza_alunos'),
    path('alunos/<pk>/deleta/', views.deleta_alunos, name='deleta_alunos'),
]

login/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.urls import path
from . import views  # Importe suas views
from django.urls import path
from django.contrib.auth import views as auth_views
app_name = 'login' 
urlpatterns = [
    # path('logar_usuario', logar_usuario, name="logar_usuario"),
    # path('cadastrar_usuario', cadastrar_usuario, name="cadastrar_usuario"),
    # path('index', index, name="index"),
    # path('logout/', views.logout_view, name='logout'),
 
    path('', views.home, name='home'),  # URL para a home
    path('registro/', views.registro_view, name='registro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_complete'),

]

templates/partials/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
      <!-- Logo/Brand -->
      <a class="navbar-brand" href="{% url 'login:home' %}">Home</a>
      
      <!-- Botão Toggler para Offcanvas -->
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
      </button>
      
      <!-- Offcanvas Menu -->
      <div class="offcanvas offcanvas-end bg-dark text-white" tabindex="-1" id="offcanvasNavbar">
          <div class="offcanvas-header">
              <h5 class="offcanvas-title">Menu</h5>
              <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
              <div class="navbar-nav">
                  {% if user.is_authenticated %}
                      <a class="nav-link" href="{% url 'dever:dever_list' %}">Deveres</a>
                      <a class="nav-link" href="{% url 'dever:lista_escolas' %}">Escolas</a>
                      <a class="nav-link" href="{% url 'dever:lista_alunos' %}">Alunos</a>
                      <a class="nav-link" href="{% url 'dever:lista_turma' %}">Turmas</a>
                      <a class="nav-link" href="{% url 'dever:lista_livro' %}">Livros</a>
                      <a class="nav-link" href="{% url 'dever:lista_materia' %}">Matérias</a>
                      <a class="nav-link" href="{% url 'dever:lista_professor' %}">Professores</a>
                      <a class="nav-link" href="{% url 'login:lista_usuarios' %}">Usuários</a>
                      <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                  {% else %}
                      <a class="nav-link" href="{% url 'login:login' %}">Login</a>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
</nav>